Repository open-spaced-repetition/fsrs-optimizer, pull requests merged in 2023-08, with the labels that each got.

#12 Feat/save metrics
  .gitignore
  pyproject.toml
  src/fsrs_optimizer/__main__.py
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: enhancement

#15 Feat/filter out cards with specific flags
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: enhancement

#17 Fix/init s out of order
  .gitignore
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: invalid

#18 Feat/optimize with revlog.csv
  .gitignore
  pyproject.toml
  src/fsrs_optimizer/__main__.py
Labels: enhancement

#20 Feat/extrapolate values of s0
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: enhancement

#22 Fix/wrong cwd when using wildcard
  pyproject.toml
  src/fsrs_optimizer/__main__.py
Labels: bug

#25 Feat/time series split for research
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: enhancement

#26 Feat/Command line flag filtering
  pyproject.toml
  src/fsrs_optimizer/__main__.py
Labels: enhancement

#27 Feat/new outlier filter based on count
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: enhancement

#29 Fix/loosen the clamping for w[10] and w[8]
  pyproject.toml
  src/fsrs_optimizer/fsrs_optimizer.py
Labels: invalid
